apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: chtest
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: chtest
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: chtest_chuucar
            name: chtest
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
